# Generated by Django 4.2.16 on 2024-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.TextField(max_length=2000),
        ),
    ]
